mybatis:
  type-aliases-package: com.haige.entity   # 起别名
  mapper-locations: /com/haige/repository/mapper/*.xml  # mapper映射文件的位置
server:
  port: 8080
spring:
  application:
    name: haige
  datasource:
    haige:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/haige?useSSL=false&characterEncoding=utf8
      username: root
      password: root
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      #exceptionSorter: false
      testOnReturn: false
      poolPreparedStatements: true
      #filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      useGlobalDataSourceStat: true
pagehelper:
  auto-dialect: "true"
  reasonable: "true"
  support-methods-arguments: "true"
  params: "count=countSql"
logging:
  config: classpath:log4j2.yml
